---
title: "Working Title: Trends and variability in chlorophyll a in a back-barrier lagoonal estuary in the southeastern United States"
format:
  docx:
    reference-doc: custom-reference-doc.docx
editor: 
  markdown: 
    wrap: 72
bibliography: references.bib
csl: estuaries-and-coasts.csl
---

Effective management of coastal ecosystems to sustain current status or
to mitigate impacts requires information on how these systems have
changed over time. This is especially true to differentiate between
anthropogenic impacts and natural variability within these systems.
Estuaries, the natural buffer zone between rivers and ocean, are often
some of the most vulnerable ecosystems as their watersheds are much
larger than their area. The problem of nutrient enrichment and pollution
in coastal environments is growing worldwide, particularly as
populations increase in these watersheds and more of the upland habitats
are developed for residential, urban, or industrial complexes
[@freeman2019; @kyzar2021].

**Nutrient enrichment alters coastal ecosystems often first with
increases in algal production and biomass (CITATION?)** and the response
of these systems is quite variable over space and time [@cloern2010].
Anthropogenic impacts are not the only the primary drivers in these
systems as climate also plays a large role in long-term conditions. In
the Chesapeake Bay, precipitation and tropical cyclone activity results
in variable phytoplankton production coupled with underlying increases
in chlorophyll *a* (a common proxy for phytoplankton biomass) due to
eutrophication [@harding2016]. In the Indian River Lagoon and St. Lucie
estuaries, variability in phytoplankton blooms have been attributed to
cyclical patterns (e.g. El Niño/La Niña periods) and tropical cyclone
events, typically as these events bring large amounts of precipitation
[@phlips2020; @phlips2021]. There are also systems, like the San
Francisco estuary which, though nutrient-enriched, do not experience
water quality impacts common to other enriched systems (like frequent
phytoplankton blooms or low dissolved oxygen) attributed to a variety of
variables such as strong tidal flushing and heavy phytoplankton grazing
pressure from bivalves [@jassby2008; @cloern2010; @cloern2019].
Additionally, the issue of nutrient pollution is not isolated to
developed watersheds as even watersheds with low levels of development
have been found to exhibit high levels of nutrient and chlorophyll *a*
concentrations, such as the tidal creeks in the Ashepoo-Combahee-Edisto
Basin in South Carolina [@keppler2015]. Therefore the use of
observational information from long-term research and monitoring
programs provides the most valuable information for place-based and
adaptive strategies in the management of coastal ecosystems.

The System-Wide Monitoring Program (SWMP) of the National Estuarine
Research Reserve System (NERRS) is an established long-term monitoring
program that has been a cornerstone of the NERRS since its inception in
1995. The SWMP utilizes standardized equipment and protocols to collect
high-frequency and continuous water quality and meteorological data in a
variety of estuarine environments across the United States and Puerto
Rico. Due to the standardization of the program, and its well-developed
and documented data management protocols for quality assurance and
quality control, it serves as an excellent resource for helping to
identify trends, patterns, and scales of variability in phytoplankton
dynamics as well as their potential drivers within estuarine
environments [@NERRS2022].

One of thirty NERRS nationwide, three of which exist in Florida, the
Guana Tolomato Matanzas National Estuarine Research Reserve (GTMNERR)
has collected long-term data on water quality and meteorological
conditions in the Guana-Tolomato-Matanzas (GTM) estuary since 2002. The
GTM is a bar-built estuary with enclosed lagoons "rivers" (the Guana,
Tolomato, and Matanzas) that trifurcate at the St. Augustine Inlet
(**MAP REFERENCE HERE**). The St. Augustine Inlet is one of two inlets
in this system and it is stabilized with a jetty and maintained by the
US Army Corps of Engineers to a depth of 5-m and the other, the Matanzas
Inlet, is one of Florida's few remaining unstructured inlets on the
Atlantic Coast [@dean1987]. Overall, the GTM estuary is a well-mixed and
well-flushed estuary with an absence of a freshwater river and a short
residence time of approximately 12.6 days [@phlips2004; @sheng2008;
@gray2021]. The estuary is within a temperate-subtropical climatic
ecotone dominated by salt marsh and mangrove habitats, intertidal oyster
reefs, tidal creeks, mud flats, and open water [@williams2014;
@bacopoulos2019]. The GTM estuary hosts exceptionally intact and robust
populations of eastern oysters (*Crassostrea virginica*) that filter
\~60% of the estuary's volume within a single residence time
[@gray2021]. It is likely these filtration services coupled with the
short residence times keep phytoplankton biomass low [@dix2013;
@hart2015].

@cloern2010 provided a conceptual framework for establishing and
comparing variability in chlorophyll *a* by investigating 84
estuarine-coastal sites and established underlying patterns in
site-specific relative importance of disturbance, annual climate cycles,
and levels of nutrient enrichment. For example, sites with regular
seasonal patterns in chlorophyll *a* were found to largely be driven by
annual cycles such as bivalve grazing pressure which oscillate over the
annual temperature cycle. Sites with large annual variability were
commonly attributed to disturbance from natural events (e.g. hurricanes)
or human actions (implementation of policies that reduced nutrient input
into waterways). This study uses the established long-term monitoring
framework of the NERRS SWMP to establish trends, patterns, and scales in
variability of chlorophyll *a* for a 20-year time period (2003-2022).

The GTM estuary has previously been described as similar to other
temperate estuaries along the southeastern United States in
physiochemical variability with factors such as temperature and salinity
[@apple2008]. Patterns in community structure and seasonality of
ichthyoplankton ingression have also been found to resemble those of
temperate, tidally-influenced estuaries such as North-Inlet, South
Carolina [@korsman2017]. In @cloern2010, North-Inlet was one of the 84
sites in which strong seasonal patterns were connected with filtration
rates of native oyster populations. @dix2013 previously described
bivalve grazing pressure from oysters and high tidal exchange supporting
small inter-annual variability in chlorophyll *a* in the GTM estuary.
Therefore, coupled with low residence times it is hypothesized that
chlorophyll *a* patterns in the GTM estuary over two decades would
exhibit low inter- and intra-annual variability. However, as is common
around the coastal US, there has been a significant increase in coastal
population density pressure in the region [@kyzar2021]. Coupled with the
changes in the watershed, increases in chlorophyll *a* concentrations
are expected over time.

# Methods

## Study Area

The SWMP of the GTMNERR operates and maintains four water quality
stations equipped with YSI EXO2 sondes, deployed within one meter of the
bottom, that record environmental parameters (e.g. temperature,
salinity) every 15-minutes. It is at these stations in which monthly
water samples are collected during an ebb tide for chlorophyll *a* and a
suite of other parameters such as nitrogens, phosphorus, bacteria, and
total suspended solids.

Established in 2002, the station locations were selected to represent
the influence of watersheds with varying degrees of urban development
and reflect a diversity of physical processes (e.g., tidal exchange,
freshwater input) and climatic conditions. Pine Island (PI) is located
off of channel marker 25 in the Tolomato River surrounded by
silviculture-dominated uplands in the northern portion of the GTM
estuary. The Guana River runs parallel to the Tolomato on the seaward
side, with the two lagoons joining 11.3-km north of the St. Augustine
Inlet, approximately X-km south of the PI station. The Tolomato River
Basin converges with the Matanzas River and Salt Run from the south
before flowing into the Atlantic Ocean at the St. Augustine Inlet.

San Sebastian (SS) is located at the confluence of the San Sebastian and
Matanzas Rivers. The San Sebastian River drains an urbanized watershed
in the western portion of St. Augustine. The Matanzas River estuary is
approximately 32 km in length and extends 13 km south of the Matanzas
Inlet. The tidal node within the Matanzas is located around the CR-206
bridge with waters flowing northward of the bridge and southward of the
bridge at outgoing tides. Fort Matanzas (FM) is located at Channel
Marker 75 approximately 4-km north of the Matanzas Inlet.

Pellicer Creek is located in the southern part of the Matanzas River
Basin, serves as a border between St. Johns and Flagler counties, and is
surrounded by public conservation lands. Pellicer Creek is a tidal creek
and is the primary source of natural freshwater drainage into the
Matanzas River. SJRWMD collects in the mouth of Pellicer Creek near
Marineland, Florida. The Pellicer Creek water quality station (PC) is at
the end of a recreational dock in Faver-Dykes State Park located within
the Pellicer Creek Aquatic Preserve.

## Field and Laboratory Procedures

All chlorophyll *a* data were "grab" samples except for Pellicer Creek
in which some missing data values were filled in with data collected at
similar time frames using an automated water sampler. This diel sampling
is also performed by the SWMP on the same tidal stage at the Pellicer
Creek station. All samples were collected monthly, in duplicate, from as
close to sonde depth as possible (no deeper than 3 meters in the deeper
sites). Samples were filtered in the field whenever feasible; otherwise,
they were placed on ice in the dark and filtered immediately upon
returning to the laboratory. All chlorophyll *a* samples were performed
using Standard Methods (SM10200H). All duplicate values were averaged
into a monthly value at all sites. Temperature (°C) and salinity
(practical salinity units, psu) data from each site was averaged to each
month. Data was removed that failed to meet quality standards for all
parameters. For the SWMP, values below the nominal base minimum
detection limit of 0.55 (µg\\L) were replaced with this nominal base to
standardize across the dataset.

## Climate Data

Continuous meteorological data is also collected by the GTMNERR SWMP at
the Pellicer Creek weather station, approximately 4 km southeast of the
Pellicer Creek water quality station, at the mouth of Pellicer Creek in
Princess Place Preserve in Flagler County. Rainfall (mm) data were
totalled for each month and year after removing data that failed to meet
quality standards. Information on El Niño/Southern Oscillation (ENSO)
was downloaded from the National Oceanic and Atmospheric
Administration's Pacific Coast Laboratory
(https://psl.noaa.gov/enso/mei/). The Multivariate ENSO Index (MEI) is
based on multiple variables that are used to describe conditions in the
tropical Pacific during ENSO events. This index is computed for 12
bimonthly rolling windows per year. This rolling window was summed to
the following month (representing preceding and existing conditions) and
was used to examine climate patterns during this study period.

## Data analysis

All statistical analyses and data visualizations were carried out using
R v4.3.0 [@R]. Generalized additive models on log10-transformed
chlorophyll *a* data were performed for each station using the
`wqtrends` package with terms *s*("cont_year"), day of the year
converted into a continuous numeric variable to represent annual effect,
and the upper limit of the basis complexity (*k*) was set to 11 times
the number of years for the input data (11 \* 20 = 220) [@wqtrends;
@beck2022]. Diagnostic information of the model fit and procedure were
checked using the `mgcv` package [@mgcv]. These models computed a smooth
temporal pattern in the raw data with an uncertainty of the smoother.
The model results were then used to calculate seasonal metrics, trends,
and plot results. The predicted values from the model results were also
used to fill in data, by creating monthly averages, for missing months
at each of the stations (CITE SUPPLEMENTAL MISSING DATA INFORMATION
HERE) to complete the time series for decomposition to further
investigate patterns and scales of variability using methods from
[@cloern2010].

Seasonality was determined not only through decomposition, but also by
measuring changes in phases of annual chlorophyll *a* cycles using `wql`
package [@wql]. As an indicator of peak annual biomass, `phenoPhase()`
was used to calculate the fulcrum or "center of gravity" as the date
each year in months when the cumulative chlorophyll *a* reached half the
total annual cumulative chlorophyll *a* [@cloern2023; @greve2005]. These
fulcrums were then used to determine the time frame of annual peak
chlorophyll *a* which was used to further test for trends in seasonal
changes over time using meta-analysis with `wqtrends`.

# Results

## Time series trends

Overall, the GAMs provided a good fit to the chlorophyll *a* data and
explained greater than 70% of deviance (range: 71 - 87%) at all sites
(TABLE REFERENCE). Chlorophyll *a* ranges were much higher in PC than
the other sites. Only significant trends in annual chlorophyll *a* over
the entire time period were detected at SS and FM, however a very clear
oscillating pattern in average chlorophyll *a* was visible at all sites.

## Patterns of Variation

## Seasonality and trends

# Discussion

The last study to have performed any trend or status of the GTM estuary
was performed almost 20 years ago in 2004 using monitoring data
collected by the St. Johns River Water Management District
[@winkler2004]. Their assessment encompassed a suite of water quality
indicators which included chlorophyll *a*. At that time, the Northern
Coastal Basin, which includes the GTM estuary, was found to have some of
the best water quality out of all the basins in the District; however,
many of the sites, though deemed of good water quality, provided
insufficient data (did not have at least 10 years of data) or had
insignificant results for trend tests [@winkler2004].

Given the lack of recent information regarding the status of water
quality or nutrients within this system, the access of a robust water
quality time series, and the continued increase in coastal population
density pressure in the region [@kyzar2021], this study uses the
established long-term continuous monitoring framework of the NERRS SWMP
to establish trends, patterns, and scales in variability of chlorophyll
*a* for a 20-year time period (2003-2022) while providing some potential
drivers of that variation.

# References
