---
title: "Methods"
format:
  docx:
    toc: true
    number-sections: true
    highlight-style: github
editor: 
  markdown: 
    wrap: 72
bibliography: references.bib
csl: estuaries-and-coasts.csl
---

# Methods

## Study area

The SWMP of the GTM Research Reserve operates and maintains four water
quality stations equipped with YSI EXO2 sondes, deployed within one
meter of the bottom, that record environmental parameters (e.g.
temperature, salinity) every 15-minutes. It is at these stations in
which monthly water samples are collected during an ebb tide for
chlorophyll *a* and a suite of other parameters such as nitrogens,
phosphorus, bacteria, and total suspended solids.

Established in 2002, the station locations were selected to represent
the influence of watersheds with varying degrees of urban development
and reflect a diversity of physical processes (e.g., tidal exchange,
freshwater input) and climatic conditions. Pine Island (PI) is located
off of channel marker 25 in the Tolomato River surrounded by
silviculture-dominated uplands in the northern portion of the GTM
estuary. The Guana River runs parallel to the Tolomato on the seaward
side, with the two lagoons joining 11.3-km north of the St. Augustine
Inlet, approximately X-km south of the PI station. The Tolomato River
Basin converges with the Matanzas River and Salt Run from the south
before flowing into the Atlantic Ocean at the St. Augustine Inlet.

San Sebastian (SS) is located at the confluence of the San Sebastian and
Matanzas Rivers. The San Sebastian River drains an urbanized watershed
in the western portion of St. Augustine. The Matanzas River estuary is
approximately 32 km in length and extends 13 km south of the Matanzas
Inlet. The tidal node within the Matanzas is located around the CR-206
bridge with waters flowing northward of the bridge and southward of the
bridge at outgoing tides. Fort Matanzas (GTMFMNUT) is located at Channel
Marker 75 approximately 4-km north of the Matanzas Inlet.

Pellicer Creek is located in the southern part of the Matanzas River
Basin, serves as a border between St. Johns and Flagler counties, and is
surrounded by public conservation lands. Pellicer Creek is a tidal creek
and is the primary source of natural freshwater drainage into the
Matanzas River. SJRWMD collects in the mouth of Pellicer Creek near
Marineland, Florida. The Pellicer Creek water quality station (GTMPCNUT)
is at the end of a recreational dock in Faver-Dykes State Park located
within the Pellicer Creek Aquatic Preserve.

## Field and Laboratory Procedures

All chlorophyll *a* data were "grab" samples except for Pellicer Creek
in which some missing data values were filled in with data collected at
similar time frames using an automated water sampler. This diel sampling
is also performed by the SWMP on the same tidal stage at the Pellicer
Creek station. All samples were collected monthly, in duplicate, from as
close to sonde depth as possible (no deeper than 3 meters in the deeper
sites). Samples were filtered in the field whenever feasible; otherwise,
they were placed on ice in the dark and filtered immediately upon
returning to the laboratory. All chlorophyll *a* samples were performed
using Standard Methods (SM10200H). All duplicate values were averaged
into a monthly value at all sites. Temperature (°C) and salinity
(practical salinity units, psu) data from each site was averaged to each
month. Data was removed that failed to meet quality standards for all
parameters. For the SWMP, values below the nominal base minimum
detection limit of 0.55 (\$\\mu\$g\\L) were replaced with this nominal
base to standardize across the dataset.

## Climate Data

Continuous meteorological data is also collected by the GTMNERR SWMP at
the Pellicer Creek weather station, approximately 4 km southeast of the
Pellicer Creek water quality station, at the mouth of Pellicer Creek in
Princess Place Preserve in Flagler County. Rainfall (mm) and
photosynthetically active radiation (PAR, mM/m-2) data were totalled for
each month and year after removing data that failed to meet quality
standards. Information on El Niño/Southern Oscillation (ENSO) was
downloaded from the National Oceanic and Atmospheric Administration's
Pacific Coast Laboratory (https://psl.noaa.gov/enso/mei/). The
Multivariate ENSO Index (MEI) was used to examine climate patterns
during this study period.

## Data analysis

All statistical analyses and data visualizations were carried out using
R v4.3.0 [@R]. Generalized additive models on log10-transformed
chlorophyll *a* data were performed for each station using the
`wqtrends` package [@wqtrends][@beck2022]. Diagnostic information of the
model fit and procedure were checked using the `mgcv` package [@mgcv].
These models computed a smooth temporal pattern in the raw data with an
uncertainty of the smoother. The model results were then used to
calculate seasonal metrics, trends, and plot results. The predicted
values from the model results were also used to fill in data, by
creating monthly averages, for missing months at each of the stations
(CITE SUPPLEMENTAL MISSING DATA INFORMATION HERE) to complete the time
series for decomposition to further investigate patterns and scales of
variability using methods from [@cloern2010].

Seasonality was determined not only through decomposition, but also by
measuring changes in phases of annual chlorophyll *a* cycles using `wql`
package [@wql]. As an indicator of peak annual biomass, `phenoPhase()`
was used to calculate the fulcrum or "center of gravity" as the date
each year in months when the cumulative chlorophyll *a* reached half the
total annual cumulative chlorophyll *a* [@cloern2023] [@greve2005].
These fulcrums were then used to determine the time frame of annual peak
chlorophyll *a* which was used to further test for trends in seasonal
changes over time using meta-analysis with `wqtrends`.

# References
